const express = require('express');
const router = express.Router();
const authController = require('./../controller/authController');
router.post('/signUp', authController.signUp);
router.post('/login', authController.login);
router.get('/verify/:token', authController.verify);
router.post('/forgotPassword', authController.forgotPassword);
router.get('/editPassword/:token', authController.editPassword);
router.post('/resetPassword/:token', authController.resetPassword);
router.get('/logout', authController.logout);
module.exports = router;
